### ISSUE TITLE
Add CI runners for PRs and as a badge in README.org

### ISSUE THREAD

**Issue by munen** [twohundredok/organ#4]

**Comment by aspiers** [comment]
AFAICS this is not really resolved because currently CircleCI is only running on PRs from @munen (or perhaps it's more technically correct to say that it's only running on PRs whose source branch is within https://github.com/200ok-ch/organice not those coming from external forks?)

**Comment by munen** [comment]
You are right, CircleCI now needs to have an 'advanced configuration' feature to be set to build branches from forks.

I've just set the flag. It seems to work^^

![image](https://user-images.githubusercontent.com/505721/71615289-d837de80-2bb0-11ea-807b-13a08c77683b.png)

**Comment by aspiers** [comment]
Wonderful, thanks for fixing so quickly!

**Comment by aspiers** [comment]
BTW it might be worth making this a [required status check](https://help.github.com/en/github/administering-a-repository/about-required-status-checks), to protect against accidentally merging something which has issues.  Admittedly this is much more valuable in projects which have multiple co-maintainers, but I personally find it useful even for projects where I'm the sole maintainer ;-)

**Comment by munen** [comment]
> Wonderful, thanks for fixing so quickly!

Sure thing!

> BTW it might be worth making this a required status check, to protect against accidentally merging something which has issues. 

Good point, I just added the rule.

<img width="1260" alt="Screenshot 2019-12-31 at 11 48 13" src="https://user-images.githubusercontent.com/505721/71619192-73d24a80-2bc3-11ea-8c10-e988854666e1.png">

> Admittedly this is much more valuable in projects which have multiple co-maintainers, but I personally find it useful even for projects where I'm the sole maintainer ;-)

Luckily I'm not the only maintainer on this project^^ Only the most active one atm. I don't plan to be the only active maintainer, though. I'll continue to ask regular contributors who present PRs that require little to no feeback if they want to step up and become active maintainers, too!

In any case, adding the required status check is a good idea. Thanks for asking for it! 🙏
